version: 2
updates:
  # Maintain dependencies for python
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "chore"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "chore"
    open-pull-requests-limit: 10

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "chore"
    open-pull-requests-limit: 10
