template: |
    ## What’s Changed

    $CHANGES
categories:
    -   title: '🚀 Features'
        labels:
            - 'enhancement'
    -   title: '🐛 Bug Fixes'
        labels:
            - 'bug'
    -   title: '🧰 Maintenance'
        labels:
            - 'chore'
    -   title: '🌍 Translations'
        labels:
            - 'translation'
            - 'i18n'
    -   title: '📚 Documentation'
        labels:
            - 'documentation'
            - 'docs'
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
