# Generated by Django 3.1.5 on 2021-02-01 19:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, primary_key=True, region=None, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, primary_key=True, region=None, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.subscriber')),
            ],
        ),
    ]
