# Generated by Django 3.1.6 on 2021-02-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_subscriber_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en_gb', 'English')], default='en_gb', max_length=5)),
                ('registered', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, unique=True)),
                ('signing_center', models.CharField(choices=[('dallas court', 'Dallas Court')], default='dallas court', max_length=50)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='checkin',
            name='member',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.member'),
            preserve_default=False,
        ),
    ]
