# Generated by Django 3.1.7 on 2021-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_member_is_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_warning',
            field=models.BooleanField(default=False),
        ),
    ]
