# Generated by Django 3.1.7 on 2021-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_member_is_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_gb', 'English'), ('cy_GB', 'Welsh')], default='en_gb', max_length=5),
        ),
    ]
