# Generated by Django 3.1.7 on 2021-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210331_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_username',
            field=models.TextField(default=''),
        ),
    ]
