# Generated by Django 3.1.7 on 2021-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210412_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('chat_id', models.BigIntegerField(default=0, unique=True)),
            ],
        ),
    ]
