# Generated by Django 3.2 on 2021-04-15 14:05

import application.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_telegramgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram_username',
            field=models.TextField(blank=True, default='', validators=[application.models.validate_telegram_username]),
        ),
    ]
