# Generated by Django 3.2 on 2021-04-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210415_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.member'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
