# Generated by Django 3.2 on 2021-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210416_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='codename',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
