# Generated by Django 3.2 on 2021-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_metrichour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrichour',
            options={'verbose_name': 'Hourly metric', 'verbose_name_plural': 'Hourly metrics'},
        ),
        migrations.AlterField(
            model_name='metrichour',
            name='metric',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='metrichour',
            name='value',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
