# Generated by Django 3.2 on 2021-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20210420_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferred_channel',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('TWILIO', 'Twilio')], default='TELEGRAM', max_length=8),
        ),
    ]
