# Generated by Django 3.2 on 2021-04-22 18:27

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_member_preferred_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='preferred_channel',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('TWILIO', 'Twilio')], default='TELEGRAM', help_text='Which channel should the app contact the user via?', max_length=8),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text="Without the initial '@'", max_length=50, validators=[application.models.validate_telegram_username]),
        ),
    ]
