# Generated by Django 3.2 on 2021-05-06 15:54

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20210422_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_gb', 'English'), ('de_DE', 'German')], default='en_gb', max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text="Without the initial '@'", max_length=50, unique=True, validators=[application.models.validate_telegram_username]),
        ),
    ]
