# Generated by Django 3.2 on 2021-05-06 19:08

# If this migration fails then it is because you have telegram usernames longer than 32 characters
# These usernames are not valid, so it is safe to truncate them by running the following in a shell

# for object in Member.objects.all():
#       object.telegram_username = object.telegram_username[:32]
#       object.save()

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20210422_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text="Without the initial '@'", max_length=32, unique=True, validators=[application.models.validate_telegram_username]),
        ),
    ]
