# Generated by Django 3.2 on 2021-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20210506_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_gb', 'English'), ('de_de', 'German')], default='en_gb', max_length=5),
        ),
    ]
