# Generated by Django 3.2.2 on 2021-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_member_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_warning',
        ),
        migrations.AddField(
            model_name='member',
            name='overdue_message_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sos_alert_received_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='warning_message_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_ok',
            field=models.BooleanField(default=True, verbose_name='Is safe'),
        ),
    ]
