# Generated by Django 3.2.2 on 2021-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20210509_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_GB', 'English'), ('fr_FR', 'French')], default='en_gb', max_length=5),
        ),
    ]
