# Generated by Django 3.2.2 on 2021-05-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_member_language'),
        ('application', '0021_alter_member_telegram_username'),
    ]

    operations = [
    ]
