# Generated by Django 3.2.2 on 2021-05-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_merge_20210510_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_GB', 'English'), ('fr_FR', 'French'), ('de_DE', 'German')], default='en_gb', max_length=5),
        ),
    ]
