# Generated by Django 3.2.2 on 2021-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_member_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en_GB', 'English'), ('fr_FR', 'French'), ('de_DE', 'German')], default='en_gb', max_length=5),
        ),
    ]
