# Generated by Django 3.2.2 on 2021-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_member_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en_GB', 'English'), (None, '---'), ('ar', 'Arabic'), ('fr_FR', 'French'), ('de_DE', 'German')], default='en_gb', max_length=5),
        ),
    ]
